### ISSUE TITLE
Buildout not working

### ISSUE THREAD

**Issue by rodfersou** [zopefoundation/z3c.form#78]
Can someone please help me to make this buildout work?

There are some dependencies that make it require a new version of Zope, what makes a conflict.

**Comment by rodfersou** [comment]
Also I couldn't run the tests following what happen in travis configuration:

``` zsh
$ coverage run -m zope.testrunner --test-path=src
Test-module import failures:

Module: z3c.form.browser.tests

Traceback (most recent call last):
  File "/home/rodfersou/.anyenv/envs/pyenv/versions/2.7.12/envs/z3c.form/lib/python2.7/site-packages/z3c/form/browser/tests.py", line 25, in <module>
    from z3c.form import testing
  File "/home/rodfersou/.anyenv/envs/pyenv/versions/2.7.12/envs/z3c.form/lib/python2.7/site-packages/z3c/form/testing.py", line 42, in <module>
    from z3c.form import outputchecker
  File "/home/rodfersou/.anyenv/envs/pyenv/versions/2.7.12/envs/z3c.form/lib/python2.7/site-packages/z3c/form/outputchecker.py", line 19, in <module>
    import lxml.etree
ImportError: No module named lxml.etree


Module: z3c.form.tests.test_doc

Traceback (most recent call last):
  File "/home/rodfersou/.anyenv/envs/pyenv/versions/2.7.12/envs/z3c.form/lib/python2.7/site-packages/z3c/form/tests/test_doc.py", line 21, in <module>
    from zope.testing import renormalizing
ImportError: No module named testing


Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Ran 1 tests with 0 failures, 2 errors and 0 skipped in 0.001 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.

Test-modules with import problems:
  z3c.form.browser.tests
  z3c.form.tests.test_doc
```

**Comment by icemac** [comment]
What Python version did you use to install via `buildout`?
What does the error message look like?

(I tried it using Python 2.7 and 36.  I ran `bin/buildout -n` to get the newest versions. `bin/test` succeed.)

The errors you get using `coverage run -m zope.testrunner --test-path=src` might occur because you did not install the dependencies of `z3c.form` in your virtualenv.

The safest way should be to use [tox](https://pypi.org/project/tox/) to run the tests against all supported Python versions. But currently I get some test failures when using `tox` which I do not get when using `buildout`.

**Comment by rodfersou** [comment]
I get this error when try to run buildout:

```
Upgraded:
  zc.buildout version 2.10.0,
  setuptools version 36.8.0;
restarting.
Generated script '/home/rodfersou/.projects/z3c.form/bin/buildout'.
Develop: '/home/rodfersou/.projects/z3c.form/.'
warning: no files found matching '*.mo' anywhere in distribution
no previously-included directories found matching '.tox'
Develop: '/home/rodfersou/.projects/z3c.form/benchmark'
Unused options for buildout: 'eggs'.
Updating test.
Updating coverage-test.
Updating coverage-report.
Installing python.
Generated interpreter '/home/rodfersou/.projects/z3c.form/bin/python'.
Installing robot.
Version and requirements information containing zope2:
  Requirement of plone.app.testing: Zope2
  Requirement of five.globalrequest: Zope2>=4.0a3
  Requirement of Products.PluggableAuthService: Zope2>=2.12
  Requirement of Products.PlonePAS>=5.0.1: Zope2>=2.13.22
  Requirement of Products.MailHost: Zope2>=4.0a5
  Requirement of Products.CMFPlone: Zope2>2.13.0
  Requirement of Products.CMFCore: Zope2<4,>=2.13.12
  Requirement of Zope2: ZServer
  Requirement of Zope2: Record
  Requirement of Zope2: Products.ZCTextIndex
  Requirement of Zope2: Products.ZCatalog
  Requirement of Zope2: Products.TemporaryFolder
  Requirement of Zope2: Products.StandardCacheManagers
  Requirement of Zope2: Products.Sessions
  Requirement of Zope2: Products.PythonScripts
  Requirement of Zope2: Products.MIMETools
  Requirement of Zope2: Products.MailHost
  Requirement of Zope2: Products.ExternalMethod
  Requirement of Zope2: Products.BTreeFolder2
  Requirement of Zope2: initgroups
  Requirement of Zope2: zope.viewlet
  Requirement of Zope2: zope.traversing
  Requirement of Zope2: zope.testing
  Requirement of Zope2: zope.testbrowser
  Requirement of Zope2: zope.tales>=3.5.0
  Requirement of Zope2: zope.tal
  Requirement of Zope2: zope.structuredtext
  Requirement of Zope2: zope.size
  Requirement of Zope2: zope.site
  Requirement of Zope2: zope.sequencesort
  Requirement of Zope2: zope.sendmail
  Requirement of Zope2: zope.security
  Requirement of Zope2: zope.schema
  Requirement of Zope2: zope.publisher
  Requirement of Zope2: zope.ptresource
  Requirement of Zope2: zope.proxy
  Requirement of Zope2: zope.processlifetime
  Requirement of Zope2: zope.pagetemplate
  Requirement of Zope2: zope.location
  Requirement of Zope2: zope.lifecycleevent
  Requirement of Zope2: zope.interface
  Requirement of Zope2: zope.i18nmessageid
  Requirement of Zope2: zope.i18n[zcml]
  Requirement of Zope2: zope.exceptions
  Requirement of Zope2: zope.event
  Requirement of Zope2: zope.deferredimport
  Requirement of Zope2: zope.contenttype
  Requirement of Zope2: zope.contentprovider
  Requirement of Zope2: zope.container
  Requirement of Zope2: zope.configuration
  Requirement of Zope2: zope.component
  Requirement of Zope2: zope.browserresource
  Requirement of Zope2: zope.browserpage
  Requirement of Zope2: zope.browsermenu
  Requirement of Zope2: zope.browser
  Requirement of Zope2: zLOG
  Requirement of Zope2: zExceptions
  Requirement of Zope2: zdaemon
  Requirement of Zope2: transaction
  Requirement of Zope2: tempstorage
  Requirement of Zope2: setuptools
  Requirement of Zope2: pytz
  Requirement of Zope2: docutils
  Requirement of Zope2: ZopeUndo
  Requirement of Zope2: ZODB3
  Requirement of Zope2: ZConfig
  Requirement of Zope2: RestrictedPython
  Requirement of Zope2: Products.OFSP>=2.13.2
  Requirement of Zope2: Persistence
  Requirement of Zope2: MultiMapping
  Requirement of Zope2: Missing
  Requirement of Zope2: ExtensionClass
  Requirement of Zope2: DocumentTemplate
  Requirement of Zope2: DateTime
  Requirement of Zope2: Acquisition
  Requirement of Zope2: AccessControl>=2.13.16
  Requirement of Products.GenericSetup: Zope2>=4.0a6
  Requirement of five.localsitemanager: Zope2>=4.0a5
While:
  Installing robot.
Error: There is a version conflict.
We already have: Zope2 2.13.27
but five.globalrequest 99.1 requires 'Zope2>=4.0a3'.
```

**Comment by icemac** [comment]
This is strange, `z3c.form` does not include a section named `robot`, there are only `test coverage-test coverage-report python` and `z3c.form` does not depend on `Zope2`.

**Comment by rodfersou** [comment]
@icemac I see.. this is my setup that is not working
